const words = [
  { word: "anticonstitucionalissimamente", clue: "De maneira extremamente contrária à constituição" },
  { word: "hipopotomonstrosesquipedaliofobia", clue: "Medo irracional de palavras longas" },
  { word: "otorrinolaringologista", clue: "Especialista médico que trata doenças do ouvido, nariz e garganta" },
  { word: "paralelepípedo", clue: "Bloco de pedra usado no calçamento de ruas" },
  { word: "psicopedagogo", clue: "Profissional que trabalha com a aprendizagem humana" },
  { word: "anticonvulsivante", clue: "Medicamento usado para prevenir convulsões" },
  { word: "fotossíntese", clue: "Processo de conversão de luz solar em energia pelas plantas" },
  { word: "desoxirribonucleico", clue: "Ácido que contém o material genético dos seres vivos" },
  { word: "inconstitucionalidade", clue: "Qualidade do que é contrário à constituição" },
  { word: "eletroencefalograma", clue: "Exame que mede a atividade elétrica do cérebro" },
  { word: "cibernético", clue: "Relacionado à tecnologia e à computação" },
  { word: "interdisciplinar", clue: "Que envolve diversas áreas do conhecimento" },
  { word: "xilofone", clue: "Instrumento musical de percussão com barras de madeira" },
  { word: "microscópio", clue: "Instrumento utilizado para observar objetos muito pequenos" },
  { word: "aceleração", clue: "Mudança na velocidade de um objeto" },
  { word: "criptografia", clue: "Técnica de codificação de informações" },
  { word: "ornitorrinco", clue: "Animal peculiar que bota ovos e possui bico" },
  { word: "antropomorfismo", clue: "Atribuição de características humanas a seres não humanos" },
  { word: "historiografia", clue: "Estudo e escrita da história" },
  { word: "microrganismo", clue: "Ser vivo muito pequeno, como bactérias e fungos" },
  { word: "efervescente", clue: "Que provoca bolhas ou borbulhas" },
  { word: "biocompatibilidade", clue: "Capacidade de um material de não provocar reação adversa no organismo" },
  { word: "aerossol", clue: "Partículas finas de substância suspensas no ar" },
  { word: "tetrápode", clue: "Animal que possui quatro membros" },
  { word: "bipolaridade", clue: "Característica de algo que possui dois polos opostos" },
  { word: "transcendental", clue: "Que vai além dos limites da experiência humana" },
  { word: "paleontologia", clue: "Estudo dos fósseis e dos seres vivos do passado" },
  { word: "zoofilia", clue: "Atração sexual por animais" },
  { word: "fisiopatologia", clue: "Estudo das alterações no funcionamento do corpo durante uma doença" },
  { word: "cromossomo", clue: "Estrutura que carrega o material genético nas células" },
  { word: "nanotecnologia", clue: "Tecnologia que trabalha com partículas minúsculas, no nível molecular" },
  { word: "flutuação", clue: "Variação de um valor ou nível ao longo do tempo" },
  { word: "psicopatia", clue: "Transtorno de personalidade caracterizado pela ausência de empatia" },
  { word: "helicóptero", clue: "Aeronave que voa por meio de hélices" },
  { word: "ecossistema", clue: "Conjunto de seres vivos e seu ambiente" },
  { word: "fenômeno", clue: "Acontecimento observável e estudado na ciência" },
  { word: "bioética", clue: "Estudo dos dilemas morais envolvendo a biotecnologia e a medicina" },
  { word: "epigenética", clue: "Área que estuda mudanças no funcionamento do genoma sem alterar o DNA" },
  { word: "hiperatividade", clue: "Estado de extrema agitação ou excesso de energia" },
  { word: "semiótica", clue: "Estudo dos signos e dos processos de significação" },
  { word: "dinossauro", clue: "Grupo de répteis extintos que dominaram a Terra" },
  { word: "eletronegatividade", clue: "Tendência de um átomo de atrair elétrons em uma ligação química" },
  { word: "biosfera", clue: "Região da Terra onde existem organismos vivos" },
  { word: "recursividade", clue: "Propriedade de um processo que se repete em suas próprias definições" },
  { word: "substancialismo", clue: "Teoria filosófica que atribui substância como a base da realidade" },
  { word: "psiconeuroimunologia", clue: "Estudo das interações entre os sistemas psicológico, nervoso e imunológico" },
  { word: "antropocentrismo", clue: "Visão de mundo que coloca o ser humano no centro" },
  { word: "heterogeneidade", clue: "Qualidade do que é composto por elementos distintos" },
  { word: "hiperglicemia", clue: "Nível excessivamente elevado de glicose no sangue" },
  { word: "ortodontia", clue: "Especialidade odontológica voltada para correção dos dentes" },
  { word: "fossilização", clue: "Processo de formação de fósseis" },
  { word: "metafísica", clue: "Ramo da filosofia que estuda a natureza da realidade" },
  { word: "quimiotaxia", clue: "Movimento dos organismos em resposta a substâncias químicas" },
  { word: "micotoxina", clue: "Substância tóxica produzida por fungos" },
  { word: "hipotálamo", clue: "Parte do cérebro que controla várias funções do corpo" },
  { word: "geopolítica", clue: "Estudo da política e das relações internacionais em escala global" },
  { word: "nanomaterial", clue: "Material manipulado em escala nanométrica" },
  { word: "fonoterapia", clue: "Tratamento de distúrbios da voz e da fala" },
  { word: "apoptose", clue: "Processo programado de morte celular" },
  { word: "sociologia", clue: "Estudo das relações e comportamentos sociais" },
  { word: "arqueologia", clue: "Estudo das civilizações antigas por meio de seus vestígios materiais" },
  { word: "audiometria", clue: "Teste que mede a capacidade auditiva de uma pessoa" },
  { word: "heliocentrismo", clue: "Teoria que afirma que o Sol é o centro do sistema solar" },
  { word: "metodologia", clue: "Conjunto de métodos utilizados em uma área de estudo" },
  { word: "velocidade", clue: "Rapidez com que um objeto se move" },
  { word: "pneumonia", clue: "Infecção nos pulmões que causa dificuldade para respirar" },
  { word: "biomassa", clue: "Material orgânico utilizado para gerar energia" },
  { word: "criptomoeda", clue: "Moeda digital descentralizada baseada em criptografia" },
  { word: "neurociência", clue: "Estudo do sistema nervoso e seu impacto no comportamento" },
  { word: "supercondutividade", clue: "Propriedade de certos materiais conduzirem eletricidade sem resistência" },
  { word: "cosmologia", clue: "Estudo da origem, estrutura e evolução do universo" },
  { word: "biorremediação", clue: "Uso de organismos vivos para remover poluentes do ambiente" },
  { word: "algoritmo", clue: "Sequência de passos para resolver um problema" },
  { word: "exobiologia", clue: "Estudo da possibilidade de vida fora da Terra" },
  { word: "fotonovela", clue: "História ilustrada ou em quadrinhos com temática dramática" },
  { word: "neuroplasticidade", clue: "Capacidade do cérebro de se reorganizar" },
  { word: "hipotermia", clue: "Temperatura corporal abaixo do normal" },
  { word: "telepatia", clue: "Comunicação mental entre pessoas, sem o uso de palavras" },
  { word: "exoesqueleto", clue: "Estrutura externa que proporciona suporte ao corpo" },
  { word: "falsificação", clue: "Ato de criar uma cópia ilegítima de algo" },
  { word: "zoogeografia", clue: "Estudo da distribuição geográfica dos animais" },
  { word: "megalomania", clue: "Desejo excessivo de poder e domínio" },
  { word: "ginecologia", clue: "Especialidade médica voltada para a saúde da mulher" },
  { word: "odontoide", clue: "Parte da coluna vertebral próxima à cabeça" },
  { word: "radiação", clue: "Emissão de energia na forma de ondas ou partículas" },
  { word: "micrometeorito", clue: "Pequeno fragmento de material cósmico que atinge a Terra" },
  { word: "espectrofotômetro", clue: "Instrumento que mede a intensidade de luz em diferentes comprimentos de onda" },
  { word: "nefrite", clue: "Inflamação dos rins" },
  { word: "aquicultura", clue: "Cultivo de organismos aquáticos para consumo" },
  { word: "termodinâmica", clue: "Estudo das relações entre calor, trabalho e energia" },
  { word: "arqueossítio", clue: "Local onde são encontrados vestígios de culturas antigas" },
  { word: "hidrosfera", clue: "Camada da Terra composta por água" },
  { word: "videoclipe", clue: "Vídeo musical que acompanha uma canção" },
  { word: "terapia", clue: "Tratamento de doenças por meio de técnicas específicas" },
  { word: "microbiota", clue: "Conjunto de microrganismos que habitam um organismo ou ambiente" }
];

  export default function getWord() {
    const index = Math.floor(Math.random() * words.length);
    return words[index];
  }
